### ISSUE TITLE
Non-Responsive design on iPhone

### ISSUE THREAD

**Issue by StilgarISCA** [CloudCannon/cause-jekyll-template#1]
### Description
When viewing this site on an a real iPhone the design is not actually responsive. It renders just like it does in a wide web browser version on the desktop. If you shrink and expand the browser window on the desktop the design is responsive as expected. It also appears to work in emulated modes supported by various browser development kits. However, on an actual iOS/Safari iPhone the design does not collapse.

### Steps to reproduce
1. Browse to [https://clean-oryx.cloudvent.net](https://clean-oryx.cloudvent.net/) on an iPhone running iOS 11.

### Expected result
Design collapses to single column

### Actual result
Site renders at full-width

### Screenshot
![img_2208](https://user-images.githubusercontent.com/4245847/36346835-6de22a90-1415-11e8-912d-5ecaead2889d.PNG)

**Comment by mneumegen** [comment]
Thanks for letting us know about this. I've just pushed a fix.

**Comment by StilgarISCA** [comment]
Stop working on the weekends :smile:. Thanks for the fix.
